docs: Add example for custom initialization options #307
ballerina-platform/lsp4intellij pull request #310
Opened 2023-05-04 03:44 UTC by dongwa

## Purpose
Resolves #307

## Goals
Just add some example  for custom initialization options

2023-05-04 03:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ballerina-platform/lsp4intellij?pullRequest=310) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ballerina-platform/lsp4intellij?pullRequest=310) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ballerina-platform/lsp4intellij?pullRequest=310) it.</sub>

2023-05-05 18:11 UTC, payne911 requested changes

2023-05-05 18:11 UTC, payne911 commented on README.md
> +            // Return your custom initialization options here.
I think this should provide an actual example. For example: how would someone set the `InitializeParams#clientInfo` field's value?

2023-05-05 18:47 UTC, payne911 commented
This seems to only provide the ability to assign a value for `initializationOptions`.

I think the library needs to instead provide a way to set the value of any field in this `InitializeParams` class.

2023-05-06 01:58 UTC, dongwa commented
> 
Yes, it only handles InitializationOptions, not InitializeParams. You would be better off opening another issue or pull request to address your question.

2023-05-06 03:11 UTC, NipunaRanasinghe commented
> > 
> 
> Yes, it only handles InitializationOptions, not InitializeParams. You would be better off opening another issue or pull request to address your question.

I feel like having to create your own process builder just to pass InitializationOptions might not be a good design. Probably we can expose APIs from the `LanguageServerDefinition` to set  both `InitializationOptions` and `InitializeParams`. 

@dongwa @payne911 Any thoughts?

2023-05-06 03:37 UTC, dongwa commented
> > > 
> > 
> > 
> > Yes, it only handles InitializationOptions, not InitializeParams. You would be better off opening another issue or pull request to address your question.
> 
> I feel like having to create your own process builder just to pass InitializationOptions might not be a good design. Probably we can expose APIs from the `LanguageServerDefinition` to set both `InitializationOptions` and `InitializeParams`.
> 
> @dongwa @payne911 Any thoughts?

Yes it's better,but now

> 

Yes, if `LanguageServerDefinition` has an API to set `InitializationOptions` and `InitializeParams`, I think it would be better. I am glad to help, but it would not be easy. We need a server to test.

2023-05-06 04:08 UTC, payne911 commented
# What I've tried
Nothing worked, unfortunately. :(

### CustomServerWrapper
I've been trying to figure out how to provide my own ServerWrapper via the ExtensionManager, but it seems like that's not possible.

### Override `LanguageServer#initialize`
Then instead in my custom RequestManager (which is registered via my ExtensionManager) I tried:
```kotlin
override fun initialize(params: InitializeParams): CompletableFuture<InitializeResult> {
  // do as I wish to modify those params
  return super.initialize(params)
}
```
... but somehow I can't get this to work. (Yet I do have other methods which I've successfully overridden in my Request Manager.)
Shouldn't the above effectively allow us to "post-process" the InitializeParams as we wish before the `initialize` method request is sent to the server? The relevant code pointer:
https://github.com/ballerina-platform/lsp4intellij/blob/d0ca56be2c65d63dfac405d3811f3b67ca372a54/src/main/java/org/wso2/lsp4intellij/client/languageserver/wrapper/LanguageServerWrapper.java#L533

---

# Proposition
@NipunaRanasinghe I believe that providing a method like `modifyInitializeParam(initParams: InitializeParams)` would be good enough:

```
    public void modifyInitializeParam(InitializeParams params) {
        // nothing in here
    }

    public void start() {
        // stuff before
                modifyInitializeParam(initParams); // this gets added
                initializeFuture = languageServer.initialize(initParams).thenApply(res -> {
        // stuff after
    }
```

People could override this new method and modify the pre-processing that this library already does. This way, it's easy to keep part of the automation we already benefit from, while also giving all the possible freedom to the library's users.

2023-05-10 15:46 UTC, payne911 commented
@NipunaRanasinghe see #311

2023-05-23 05:16 UTC, NipunaRanasinghe reviewed
@dongwa Is it possible to update the PR with changes introduced by https://github.com/ballerina-platform/lsp4intellij/pull/311?

2023-05-23 06:12 UTC, dongwa commented
> @dongwa Is it possible to update the PR with changes introduced by #311?

ok, give me some times

2023-05-23 06:21 UTC, NipunaRanasinghe commented
> > @dongwa Is it possible to update the PR with changes introduced by #311?
> 
> ok, give me some times

Great! thanks

2023-05-23 07:12 UTC, dongwa commented
Okay, I have updated it. Please help me review it.
@NipunaRanasinghe @payne911

2023-05-23 07:49 UTC, NipunaRanasinghe approved these changes

2023-05-28 06:26 UTC, payne911 requested changes
GitHub's code suggestion feature does not seem to play well with the markdown code notation. But you'll get the gist of it.

I believe a readme should be light: we should avoid showing lengthy examples. Minimal examples, with reference points is preferable. The JavaDoc provided by the library should be sufficient if users are trying to dig deeper for their understanding.

2023-05-28 06:26 UTC, payne911 commented on README.md
> +  ```
```suggestion
- **Custom Initialization Params**

If your LSP server needs some custom initialization options when connecting, you can define a class that extends `ProcessBuilderServerDefinition` or `RawCommandServerDefinition`, and then override the `customizeInitializeParams` method to modify any property of the `InitializeParams`.

Here's an example:

```java
public class MyServerDefinition extends ProcessBuilderServerDefinition {
    public MyServerDefinition(String ext, ProcessBuilder process) {
        super(ext, process);
    }

    @Override
    public void customizeInitializeParams(InitializeParams params) {
        params.clientInfo = new ClientInfo("MyName", "MyVersion");
    }
}
```

Finally, assign your class as a ServerDefinition:

```java
ProcessBuilder process = new ProcessBuilder("path/to/launcher-script.sh");
IntellijLanguageClient.addServerDefinition(new MyServerDefinition("xxx", processBuilder));
```

You can refer to #311 for more details.
```

2023-06-12 02:15 UTC, NipunaRanasinghe approved these changes

2023-06-12 02:15 UTC, merged